// Code generated by "stringer -type Dumptype"; DO NOT EDIT

package main

import "fmt"

const (
	_Dumptype_name_0 = "DUMPTYPE_NONE"
	_Dumptype_name_1 = "DUMPTYPE_MYSQLDUMPTYPE_PGSQL"
)

var (
	_Dumptype_index_0 = [...]uint8{0, 13}
	_Dumptype_index_1 = [...]uint8{0, 14, 28}
)

func (i Dumptype) String() string {
	switch {
	case i == -1:
		return _Dumptype_name_0
	case 1 <= i && i <= 2:
		i -= 1
		return _Dumptype_name_1[_Dumptype_index_1[i]:_Dumptype_index_1[i+1]]
	default:
		return fmt.Sprintf("Dumptype(%d)", i)
	}
}
